{{- if .Values.server.ingressGrpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "netbird.server.fullname" . }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netbird.server.labels" . | nindent 4 }}
  {{- with .Values.server.ingressGrpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.server.ingressGrpc.className }}
  ingressClassName: {{ .Values.server.ingressGrpc.className }}
  {{- end }}
  {{- if .Values.server.ingressGrpc.tls }}
  tls:
    {{- range .Values.server.ingressGrpc.tls }}
    - secretName: {{ .secretName }}
      hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.server.ingressGrpc.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "netbird.server.fullname" $ }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}

